name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tp-githubactions   # <-- PUT YOUR APP FOLDER HERE
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Build Angular (project page baseHref)
        run: npm run build -- --configuration=production --base-href "/GitHubActions_Angular/"

      # Robustly find the built index.html (works for Angular 16/17/18)
      - name: Determine dist path
        id: dist
        run: |
          CANDIDATE=$(find dist -maxdepth 3 -type f -name index.html -print -quit)
          if [ -z "$CANDIDATE" ]; then
            echo "::error ::No index.html found under dist/"
            exit 1
          fi
          DIST_DIR=$(dirname "$CANDIDATE")
          echo "path=$DIST_DIR" >> "$GITHUB_OUTPUT"
          echo "Resolved dist path: $DIST_DIR"
          ls -la "$DIST_DIR"

      - name: Create SPA 404 fallback
        run: cp "${{ steps.dist.outputs.path }}/index.html" "${{ steps.dist.outputs.path }}/404.html" || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.dist.outputs.path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
