name: PR Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  push:
    branches:
      - feature/**
      - main         # add this only if you want lint on main pushes too

jobs:
  lint:
    runs-on: ubuntu-latest
    # defaults: { run: { working-directory: tp-githubactions } }  # keep if your app lives in a subfolder
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
