jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tp-githubactions   # 👈 add this
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint
